// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {counter} from '../models';
import {store} from '../models';
import {traedb} from '../models';
import {main} from '../models';

export function AddManual():Promise<void>;

export function AdjustUserManual(arg1:string,arg2:number):Promise<void>;

export function AutoFreezeCurrentUser():Promise<void>;

export function DeleteSnapshot(arg1:string):Promise<void>;

export function DeleteUser(arg1:string):Promise<void>;

export function GetAlertThreshold():Promise<number>;

export function GetAllUserTodayCounts():Promise<Array<counter.UserTodayCount>>;

export function GetAutoLaunch():Promise<boolean>;

export function GetAutoThreshold():Promise<boolean>;

export function GetControlStripPinned():Promise<boolean>;

export function GetCurrentTraeUserID():Promise<string>;

export function GetDayCount(arg1:string,arg2:string):Promise<number>;

export function GetDockHidden():Promise<boolean>;

export function GetHourlyCounts(arg1:string):Promise<Array<store.LedgerHourlyCount>>;

export function GetHourlyCountsForDate(arg1:string,arg2:string):Promise<Array<store.LedgerHourlyCount>>;

export function GetLastActiveUser():Promise<string>;

export function GetLearnedQuota(arg1:string):Promise<number>;

export function GetLearnedQuotaForDate(arg1:string,arg2:string):Promise<number>;

export function GetManualQuota():Promise<number>;

export function GetMonthHistory(arg1:string):Promise<Array<store.LedgerDateCount>>;

export function GetNotifyEnabled():Promise<boolean>;

export function GetQuotaInfo():Promise<traedb.QuotaInfo>;

export function GetSelectedUser():Promise<string>;

export function GetShowAllAccounts():Promise<boolean>;

export function GetTheme():Promise<string>;

export function GetTodayCount():Promise<main.TodayCountResult>;

export function GetUserMessages():Promise<Array<main.UserMessageResult>>;

export function GetUserRemark(arg1:string):Promise<string>;

export function GetVersion():Promise<string>;

export function GetWarningThreshold():Promise<number>;

export function GetWeekHistory(arg1:string):Promise<Array<store.LedgerDateCount>>;

export function GetYearHistory(arg1:string):Promise<Array<store.LedgerMonthCount>>;

export function HasNotifiedAlert(arg1:string,arg2:string):Promise<boolean>;

export function HasNotifiedExhaustion(arg1:string,arg2:string):Promise<boolean>;

export function HasNotifiedWarning(arg1:string,arg2:string):Promise<boolean>;

export function HasSnapshot(arg1:string):Promise<boolean>;

export function HasUserCredential(arg1:string):Promise<boolean>;

export function IsTraeLoggedIn():Promise<boolean>;

export function MarkNotifiedAlert(arg1:string,arg2:string):Promise<void>;

export function MarkNotifiedExhaustion(arg1:string,arg2:string):Promise<void>;

export function MarkNotifiedWarning(arg1:string,arg2:string):Promise<void>;

export function RecordAndLearnQuota():Promise<void>;

export function Refresh():Promise<void>;

export function RestartApp():Promise<void>;

export function RestartTrae():Promise<void>;

export function SaveSelectedUser(arg1:string):Promise<void>;

export function SendNotification(arg1:string,arg2:string):Promise<void>;

export function SendNotificationWithType(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetAlertThreshold(arg1:number):Promise<void>;

export function SetAutoLaunch(arg1:boolean):Promise<void>;

export function SetAutoThreshold(arg1:boolean):Promise<void>;

export function SetControlStripPinned(arg1:boolean):Promise<void>;

export function SetDockHidden(arg1:boolean):Promise<void>;

export function SetManualCount(arg1:number):Promise<void>;

export function SetManualQuota(arg1:number):Promise<void>;

export function SetNotifyEnabled(arg1:boolean):Promise<void>;

export function SetShowAllAccounts(arg1:boolean):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetUserRemark(arg1:string,arg2:string):Promise<void>;

export function SetWarningThreshold(arg1:number):Promise<void>;

export function SnapshotForUser(arg1:string):Promise<void>;

export function SwitchUser(arg1:string):Promise<void>;

export function ToggleUserTracking(arg1:string):Promise<void>;
