// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddManual() {
  return window['go']['main']['App']['AddManual']();
}

export function AdjustUserManual(arg1, arg2) {
  return window['go']['main']['App']['AdjustUserManual'](arg1, arg2);
}

export function AutoFreezeCurrentUser() {
  return window['go']['main']['App']['AutoFreezeCurrentUser']();
}

export function DeleteSnapshot(arg1) {
  return window['go']['main']['App']['DeleteSnapshot'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function GetAlertThreshold() {
  return window['go']['main']['App']['GetAlertThreshold']();
}

export function GetAllUserTodayCounts() {
  return window['go']['main']['App']['GetAllUserTodayCounts']();
}

export function GetAutoLaunch() {
  return window['go']['main']['App']['GetAutoLaunch']();
}

export function GetAutoThreshold() {
  return window['go']['main']['App']['GetAutoThreshold']();
}

export function GetControlStripPinned() {
  return window['go']['main']['App']['GetControlStripPinned']();
}

export function GetCurrentTraeUserID() {
  return window['go']['main']['App']['GetCurrentTraeUserID']();
}

export function GetDayCount(arg1, arg2) {
  return window['go']['main']['App']['GetDayCount'](arg1, arg2);
}

export function GetDockHidden() {
  return window['go']['main']['App']['GetDockHidden']();
}

export function GetHourlyCounts(arg1) {
  return window['go']['main']['App']['GetHourlyCounts'](arg1);
}

export function GetHourlyCountsForDate(arg1, arg2) {
  return window['go']['main']['App']['GetHourlyCountsForDate'](arg1, arg2);
}

export function GetLastActiveUser() {
  return window['go']['main']['App']['GetLastActiveUser']();
}

export function GetLearnedQuota(arg1) {
  return window['go']['main']['App']['GetLearnedQuota'](arg1);
}

export function GetLearnedQuotaForDate(arg1, arg2) {
  return window['go']['main']['App']['GetLearnedQuotaForDate'](arg1, arg2);
}

export function GetManualQuota() {
  return window['go']['main']['App']['GetManualQuota']();
}

export function GetMonthHistory(arg1) {
  return window['go']['main']['App']['GetMonthHistory'](arg1);
}

export function GetNotifyEnabled() {
  return window['go']['main']['App']['GetNotifyEnabled']();
}

export function GetQuotaInfo() {
  return window['go']['main']['App']['GetQuotaInfo']();
}

export function GetSelectedUser() {
  return window['go']['main']['App']['GetSelectedUser']();
}

export function GetShowAllAccounts() {
  return window['go']['main']['App']['GetShowAllAccounts']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function GetTodayCount() {
  return window['go']['main']['App']['GetTodayCount']();
}

export function GetUserMessages() {
  return window['go']['main']['App']['GetUserMessages']();
}

export function GetUserRemark(arg1) {
  return window['go']['main']['App']['GetUserRemark'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWarningThreshold() {
  return window['go']['main']['App']['GetWarningThreshold']();
}

export function GetWeekHistory(arg1) {
  return window['go']['main']['App']['GetWeekHistory'](arg1);
}

export function GetYearHistory(arg1) {
  return window['go']['main']['App']['GetYearHistory'](arg1);
}

export function HasNotifiedAlert(arg1, arg2) {
  return window['go']['main']['App']['HasNotifiedAlert'](arg1, arg2);
}

export function HasNotifiedExhaustion(arg1, arg2) {
  return window['go']['main']['App']['HasNotifiedExhaustion'](arg1, arg2);
}

export function HasNotifiedWarning(arg1, arg2) {
  return window['go']['main']['App']['HasNotifiedWarning'](arg1, arg2);
}

export function HasSnapshot(arg1) {
  return window['go']['main']['App']['HasSnapshot'](arg1);
}

export function HasUserCredential(arg1) {
  return window['go']['main']['App']['HasUserCredential'](arg1);
}

export function IsTraeLoggedIn() {
  return window['go']['main']['App']['IsTraeLoggedIn']();
}

export function MarkNotifiedAlert(arg1, arg2) {
  return window['go']['main']['App']['MarkNotifiedAlert'](arg1, arg2);
}

export function MarkNotifiedExhaustion(arg1, arg2) {
  return window['go']['main']['App']['MarkNotifiedExhaustion'](arg1, arg2);
}

export function MarkNotifiedWarning(arg1, arg2) {
  return window['go']['main']['App']['MarkNotifiedWarning'](arg1, arg2);
}

export function RecordAndLearnQuota() {
  return window['go']['main']['App']['RecordAndLearnQuota']();
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function RestartTrae() {
  return window['go']['main']['App']['RestartTrae']();
}

export function SaveSelectedUser(arg1) {
  return window['go']['main']['App']['SaveSelectedUser'](arg1);
}

export function SendNotification(arg1, arg2) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2);
}

export function SendNotificationWithType(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendNotificationWithType'](arg1, arg2, arg3);
}

export function SetAlertThreshold(arg1) {
  return window['go']['main']['App']['SetAlertThreshold'](arg1);
}

export function SetAutoLaunch(arg1) {
  return window['go']['main']['App']['SetAutoLaunch'](arg1);
}

export function SetAutoThreshold(arg1) {
  return window['go']['main']['App']['SetAutoThreshold'](arg1);
}

export function SetControlStripPinned(arg1) {
  return window['go']['main']['App']['SetControlStripPinned'](arg1);
}

export function SetDockHidden(arg1) {
  return window['go']['main']['App']['SetDockHidden'](arg1);
}

export function SetManualCount(arg1) {
  return window['go']['main']['App']['SetManualCount'](arg1);
}

export function SetManualQuota(arg1) {
  return window['go']['main']['App']['SetManualQuota'](arg1);
}

export function SetNotifyEnabled(arg1) {
  return window['go']['main']['App']['SetNotifyEnabled'](arg1);
}

export function SetShowAllAccounts(arg1) {
  return window['go']['main']['App']['SetShowAllAccounts'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetUserRemark(arg1, arg2) {
  return window['go']['main']['App']['SetUserRemark'](arg1, arg2);
}

export function SetWarningThreshold(arg1) {
  return window['go']['main']['App']['SetWarningThreshold'](arg1);
}

export function SnapshotForUser(arg1) {
  return window['go']['main']['App']['SnapshotForUser'](arg1);
}

export function SwitchUser(arg1) {
  return window['go']['main']['App']['SwitchUser'](arg1);
}

export function ToggleUserTracking(arg1) {
  return window['go']['main']['App']['ToggleUserTracking'](arg1);
}
